### ISSUE TITLE
Mention installing chrome in system requirements.

### ISSUE THREAD

**Issue by paxapy** [Ehsan-U/scrapy-nodriver#3]
I've been trying scrapy nodriver with fresh debian image for docker and it was not obvious from both this and original nodriver documentation that I need to have chrome installed in a system.
I got errors like this:

`could not find a valid chrome browser binary. please make sure chrome is installed.or use the keyword argument`

And as it was my first experience with nodriver I took some time to research and find out that I need to install chrome by myself (I was convinced that everything is required for package to work is included in dependencies)

Maybe it worth to mention in documentation that chrome needs to be installed in a system?

BTW, for debian `chromium` was enough:
`apt install chromium`

**Comment by Ehsan-U** [comment]
Thanks @paxapy for suggestion.
